apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-tls
  namespace: ingress-system
spec:
  secretName: api-tls
  duration: 720h
  renewBefore: 240h
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  dnsNames:
    - api.aegis.home.arpa
  issuerRef:
    name: aegis-dev-ca
    kind: Issuer
    group: cert-manager.io
