apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - httproute.yaml
  - servicemonitor.yaml
  - networkpolicy.yaml
  - ciliumnetworkpolicy-gateway.yaml
  - imagerepository.yaml
  - imagepolicy.yaml
