apiVersion: v1
kind: Secret
metadata:
    name: grafana-oidc
    namespace: observability
stringData:
    client-secret: ENC[AES256_GCM,data:4SCN2sfg/za8HRW9P6wQDDyjPE6otv1ydJFOnQVIDRsSv8W0mcNzDBP3PiHY3b4I,iv:+QeNo2jU0/gjxHYLItZIPNI4pCzUz29RR1UKFvPV9Vw=,tag:UbtbLG12uiBs0AUFvBOr6w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3MFhtdXJBWUVaaC8yRGdW
            eU54SjY2VVhIRC9wb09VSk1ROXdwRVo1U1FvCkxDZk0rNkxGakFYYjZBeGpXT1Jp
            ekVjMzN3d0R6WDJuTE9PSHozVUNIcEkKLS0tIE5mN2FpU1MzdE51emI0ZnpDU1NE
            akhzczZ0VjdiOGZBNDJuVmJVb3hUWFEKNttUTFqkZuyKp785AhTuIUmEBJnkPGIQ
            2Blrzmw0KJZ8acnP80ejNBAogFpYeIqPdENMsuIBrMtJvDaA7JHdrA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gfycq3cyvq29hwkluywkhyc6rpt9y257u9ltltea769khtkysawslec0vw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-13T19:31:37Z"
    mac: ENC[AES256_GCM,data:JSHENjGqk+dvXNKM0MrnV/AAhs0BSKsELIBp8y5zQRHtygxSF4LB3l5PsnyVXjJrFkeEpGe402vevMyVDs0oNBzrHZEY5XVt+WKArpGttIadmb8cXTeH9zSW07UJ6DSL191JQJs89yd6Z1e6EWIx0P0TxCGnj++GrWasPdCxkLc=,iv:cvg+t24macNVdjFBrtosSh+YQ5v3jzDc2ck3l0+UwE8=,tag:ic1dlZ6MOr7XQUr4smxiEQ==,type:str]
    version: 3.13.3
