apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - httproute.yaml
  - namespace.yaml
  - helmrepository.yaml
  - secret.enc.yaml
  - grafana-oidc.enc.yaml
  - helmrelease.yaml
