apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: observability
stringData:
    admin-user: ENC[AES256_GCM,data:ViMYFNM=,iv:InPXM8goGo0ZJ76jHLbRob8tD7y307uJcw+4RU/npd0=,tag:+69eQLVGMI1QNcTThWUtKA==,type:str]
    admin-password: ENC[AES256_GCM,data:fsfdk10lr8sCWCHygim9tq5Ki2ni8V+eJbhD26+5bEpxtCf9KxrgsnD/XGSzCo/X,iv:/Qk74LUrJi2GRPjDWmX9w77g8K29xUG9tz2fBAM6Jho=,tag:KOv9R66ZPvRytfs/uCLU5A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwQWpjMjkwRmVsS2l1TERT
            cEowMmE2U1ZGMGlsQkVxdVdPMElSMzYwMFJFCjRLNGY2QllaK0ZLRE0rcExlNzV5
            TGc1c0NnZWtBVXF3dHo0SFJCQU5rcXcKLS0tIHNraU1FcmtUL1pzRUhSajJHV0I3
            K0RhSktmV3orVU9MeFVHbmE0b3dPWjgKCDSvADCAWcrO3vnMsARmhuEqc4VmesrH
            igEC7NcvWf5uwpJmY59SckWR2VrlraqMmTGkN+ZZnhznLXakuoCYYw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wp3ddrp7tj36gvutrxaj42q8azjfxg7dda8g0cxm0n3njyxaeaaqv3vu4k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-28T18:29:10Z"
    mac: ENC[AES256_GCM,data:BkXMaw9fhYMXQsHHYbjlNGt4Iav9BCxl60EJl9K5gd9sWoXghAp28D8usHHzVSrUJjWDn7Z+qZu5tJeITkq3MVAl4sw1AJGl8Trgz40p4f9YSEYvcn7DUUyyOt3fZ4Gvm3ISdID09ItrwqMWrbZM4leVp991Wvoy2ZgSDaolABk=,iv:Ai1pFxHVdadcrdMqPH1yns+UuYYfI0Zsko7bKOjpmjI=,tag:zOUdx34neQQR9AWWpTPV/A==,type:str]
    version: 3.13.3
