apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: observability
stringData:
    admin-user: ENC[AES256_GCM,data:PAPUVwg=,iv:Bqt3BG2qgBFAUZljTbNpDtot7H77nFjgSX7mtKa/57o=,tag:QU5k4UTgFquVtFWbi/COqQ==,type:str]
    admin-password: ENC[AES256_GCM,data:j0hnvz8Aql0UTKkWVMD9kqBTJ0UI3HwaPuM1a9AxMvc=,iv:hO4sR2xJifZYv8IcilxUjJ1OsC0rZpA0ksMJZyYOIWM=,tag:++1KohMWthbk5BbG8kJMyw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuSU1xejNIOXBOOGZjVzdZ
            bjBWdkJGRzVJRHFWWnpPbXhLZ0VIRkxhcUdZCmZZWTVHQlg0WWRaYmF6T2NHSHVn
            MVYyRXdET1VjWjBsQnM4MmpzTTZqTDQKLS0tIHJiamJZbjJlRVFCb294bGl1MkNh
            a1pMUW9qNncyeUZvb0lwUThkazVmZlkKfWBWMf0/PQlJi/ixgFsti09Y3u+w7f1X
            7vYwH3Sh0G0VhiJEGm1Vqx7ph7SR55bEsWhpoqMR5VVevwJiO7V1aA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gfycq3cyvq29hwkluywkhyc6rpt9y257u9ltltea769khtkysawslec0vw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-13T18:16:25Z"
    mac: ENC[AES256_GCM,data:IFs3v8a2a1gRe3aRFuzrPFMSJj02NOfHYLORECW8OXTF4jtlVTZAKX3CVHOn1yT2N61Gh50WsC3zCNi6oUKY/o9kkeLSh/W88rXYjLCpDJmimcBy6fG0KYJ0yHcdZgodzEawzusY73GxTpnBuBtjIkzx1PX3c/1hYwdNoYvwJ9A=,iv:cQcei4vWv+p0Kg8XC7tYGwELpnq6vDmDH0KMqMRv9T0=,tag:HZ15DVhYNoikL7ky9BUA4A==,type:str]
    version: 3.13.3
