apiVersion: v1
kind: Secret
metadata:
    name: authentik-config
    namespace: authentik
stringData:
    secret-key: ENC[AES256_GCM,data:NFJo6ExvbOM9O1w751YrHk6xKjf6GLl/DqAZneRm34vAdjLT13oOAyS2AoOorI9V9Xj9/q37XqnBGI3EFAKnfYJp+3PtYmgbs60StNefpO7VMzPE9lkZeg==,iv:/ZRtRaUBsS19Ldu8nipu2UgZCeeJarxLqmXhn30Thwk=,tag:FQ2IhxK+b/Wg66SRsr50DQ==,type:str]
    postgresql-password: ENC[AES256_GCM,data:2c1oH0uNsPtvoKJwsV1yKk5aSrIUWr5uGhY2nLUpwcGEbWrivJ+HLC8DRJ1KDLGq,iv:hkfprD/WFwZ+MugrN521urLtU0tiPB15Kh4xxtkp6ec=,tag:tt7swEs99M8H52fP73ydtA==,type:str]
    bootstrap-password: ENC[AES256_GCM,data:5LG0qZSwtA3A7dcW/oQLpn8sMmpUh0EKIW37yPfXcvorf7b5D47KlyhSePYMjPII,iv:toSz3yJAIaysmk33V3C07dPI45YJdp0jE1BBhx+InbY=,tag:+cEShYfsZZ5VnoDwxGWLAg==,type:str]
    bootstrap-token: ENC[AES256_GCM,data:s3rhy8MNGOnhE2MnueVkqUtnDXcTQ4XTCIfoLPCoiqLl279/MtTyrTDBfEEatAtMquVAWn79r/8lRtBi3rfTjA==,iv:9Pg5Q98JqKDpp/GxXVQIBLaFJLzITIJVtnaCgAl+Edk=,tag:Foe0r41YcUKkF/Pa6Z5/lw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtRVlQZVNuQWJpb28yYVla
            MU1jdnpDWTRPaUJrWHNaVEVERTRUNm1hc2lBCkw2LzJpZGJ0VUl5ajFKaUhmeThS
            RW5kVVBZUVJsQVJTS0YrUlBxU2RHYVEKLS0tIGVIZEdTUlB2VzZMcVg5cHFLbE5v
            MWVsVk1XUWY4c2M5ZEVzRy9abXorWG8K7sFzutgv2YOhb6HpvKzF/FmQZitN+j4b
            JhN6gbjnMHPV43U3rHjRYrlRBqDYZREqab0Rh/UjzoV34oyw0wgVqQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wp3ddrp7tj36gvutrxaj42q8azjfxg7dda8g0cxm0n3njyxaeaaqv3vu4k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-28T18:29:10Z"
    mac: ENC[AES256_GCM,data:QWkgbYs5M2EM4lrFosP80IPYiDT4u3V1YTjlRJ7mlLa3z0uvASqTWoa/tVFXlFhWLhQ5OYNUzt3onBGHFzrHRIUbdQQ7mNqhv+XIYa1fhKgtQZzpCNpMKAXEBuc0ZwINvIXLWncU6qGwr9Jm5BDh02z8ne4n3Mz8+pGapvoBx3U=,iv:jXqz+yujgUCv+SupiJKpFcbDGTydVrRT7ia7VLNUZFM=,tag:GH7aGbTUQT0OJKrPClrHOA==,type:str]
    version: 3.13.3
