apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - httproute.yaml
  - namespace.yaml
  - helmrepository.yaml
  - config.enc.yaml
  - blueprint.enc.yaml
  - helmrelease.yaml
  - networkpolicy-postgresql.yaml
  - networkpolicy-server.yaml
  - networkpolicy-worker.yaml
  - ciliumnetworkpolicy-server-gateway.yaml
