apiVersion: v1
kind: Secret
metadata:
    name: postgresql
    namespace: stateful-lab
stringData:
    postgres-password: ENC[AES256_GCM,data:LYl7/IBNVYiinznIWZufvP4Lwsna5bEA5iBuGMiEGStVGVjhv17uh7uZ13nMM5Zx,iv:f5OQ03XOTqZLRKoEdTh0TazfJt0sXY5Vrd+ojeTypx0=,tag:OsQnXYVm7j8fbpvlSPboog==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmM2Q2Z2tGc0sweDhMOElU
            cHk2a2plWVR3S0NZeVVxUXZwQ2RiMXpsb1FBCnk2ckRjNFNKVjBFTSs5eXl3SnNY
            NU1BYXhkZWdlQ2xMZ2NDQ3hYb25vS1kKLS0tIFowWHJXTC9maVhNQWVLNFd4YUV4
            SHlZQlo3eXQyVjdWNnF1b0hSekhYSkkKNWH/LKh111wf1IWiz/XhsGf3gW97q76R
            BhQZi3i3UBPNp9uHN7hi4TiBRjdxL92ennyla6N7IDvXM4pK9j2vKA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wp3ddrp7tj36gvutrxaj42q8azjfxg7dda8g0cxm0n3njyxaeaaqv3vu4k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-28T18:29:10Z"
    mac: ENC[AES256_GCM,data:gsl79l4w3nOhNaNyyAvwVZvz9ATjB/XbnqV68CAWqODTqpRUtgfSTcRfDr3TuFbxwLELI5rOQSfCedBd9CrX5m7YBX94UiSscmQvUticFnolDCQuAq770EDfvC4deCturBo8OjYB3xYEEqZiDv/53yqHTco1ZBlTJpRq4fluEEs=,iv:FN4d6daG1oAc9B1G7z8UAPCUVtfdxLj4O2UO1HbH3+8=,tag:XNE7llEC9XvZaUDdmV22Wg==,type:str]
    version: 3.13.3
