apiVersion: v1
kind: Secret
metadata:
    name: postgresql
    namespace: stateful-lab
stringData:
    postgres-password: ENC[AES256_GCM,data:TJPqnlDnURgy6U42CO9WZ8Pt72wv8AG1/zSaUyYznpw=,iv:xBcMN2MUkUE1Xfq3FR6cl/572RWRL44bqDovfbnXVVE=,tag:ZCZ2yo8vPPcD5O4md4wm1Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBETjNjMGZYRVRFMFBFSnJ3
            bEJ6WnZpSDNmeEhoOUg0VzRaWEU1NUJxU0RjCkYxeWZCdUtVbFRXcUdyZTNXa1la
            MHBtdE1JR1RTeW1pc0d4MndTZkdsVncKLS0tIFRzelJXaXJYcGdta09kN3hOT2ll
            bTY3dTVaUVlMcGRnWTFkd25lWDBJOGcKMYsb169yLADhKO0/Febo7m43Alo6cfhN
            sOv+g7jGwnhiCoyQkWwry67tHckebKPxZiTazxxUvoK4kPAHalqTWw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gfycq3cyvq29hwkluywkhyc6rpt9y257u9ltltea769khtkysawslec0vw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-18T07:31:49Z"
    mac: ENC[AES256_GCM,data:GTdWLUV/6100L57fFhMlRxeuOI81q83E9RGAFe8+Zv/WKDgwC7mPbIo2bGv80vzWm8sqaj9wffr2qay5o4iGRN12F1GvXBPiHHgHhvgBuSAOhTadh+yfXYHSdksIELELh1SMhL02AFYXlNYs5sCto26AhliNgIPRmMDmJkV5Jrw=,iv:8Hl50fhaS0LJ/p69naOmLQSxNv7HTx8R6A2jqjh50rE=,tag:KkRsL0MhkKvC9maxWycKZQ==,type:str]
    version: 3.13.3
