apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - issuer.yaml
  - certificate-grafana.yaml
  - certificate-auth.yaml
  - certificate-api.yaml
  - gateway.yaml
  - httproute-redirect.yaml
