apiVersion: v1
kind: Secret
metadata:
    name: podinfo-ui
    namespace: demo-app
stringData:
    PODINFO_UI_MESSAGE: ENC[AES256_GCM,data:R2y4CqTfIJSsDX4QrCq7reZxTcEHR4ECu3aJg0dYq8Hb42Gok5xrmx25IBqOww==,iv:G2SFkaBa9oyoIyzdhMACHA2so7rfUZbxRsShNTrNChk=,tag:UozzVlml79mD8e3/6wqh6A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtRks1dTM5b0h0SDhSRzBl
            Y3lxc2NzdHFHS3pxRWI4bkljSDV5VnNIUm5RCnRRUldVRDhRTVNTNmR5cGdZOTAz
            UzJyd3ZRM1p1L3QyVkZlSGFKSG4xYmMKLS0tIFZTVSsrSUR0dTFpYzYyNStKaFR1
            eFlQV0t2N2R2MC9UczZiOGgyUG9wWVkKIoVyTM5pzebXkNTHTFdnRWR9IE/2G1fe
            WVIndzwzZK3diopWJo/aVKmYk+UfX1L5oXntW/TNbum4R45mcIkePw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wp3ddrp7tj36gvutrxaj42q8azjfxg7dda8g0cxm0n3njyxaeaaqv3vu4k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-28T18:29:10Z"
    mac: ENC[AES256_GCM,data:1sj0WpBfX9x+edtoDa1XJ9YnyuRGFpbBeaiVS2BHSOn40heJNeiwHPFZnkOkSsHig07/MPIeIx2SksaEhrWPtg5dabEBpkfpoV2pddTIg60nzGWwCtMagiNH4XQFOrbwl4Tt66jB3EwtgnbMLRO/pt8ugokO9tV4ByOGNJylrvQ=,iv:UD5HR3A4doCn06pZbyqFfZg7q1n/hJxFwydBm7zuMBc=,tag:6TxHaiKRU86jJgDtSBkZOg==,type:str]
    version: 3.13.3
