apiVersion: v1
kind: Secret
metadata:
    name: podinfo-ui
    namespace: demo-app
stringData:
    PODINFO_UI_MESSAGE: ENC[AES256_GCM,data:UaFYpsFvfl4mTwD+pEQl,iv:cwroLJ63DtEUxc8C8qsoDBYU14rZ1fQ/RA5DtUOagdA=,tag:1C1N9JuuPaPXpmJHr+DTFg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkekhLUXZQekpZamFBZ1dq
            R0hMVFFWeXpOZURmbmVhb254QjEvL1lBWm53Cnh5Q0d4RlJTRE1rRzdCNU41S3Ux
            L0xsMmNncm03ZmI1bVFTaElGMGo1ZGcKLS0tIFVHOFFaS3FyVlJqMG84SWJ1Rms5
            RklMSmdMRGE3cTF4MGZuVGo0M1JOOUEKjPrltgx/2vqF36f5wyESO604GE+BxzRX
            F1QRFIKJp75arZNe4qEL2Yf0o1z3sXZHdc9tURm3dYWhJo0jq+Zksg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gfycq3cyvq29hwkluywkhyc6rpt9y257u9ltltea769khtkysawslec0vw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-13T18:07:15Z"
    mac: ENC[AES256_GCM,data:4lfAeA1uTN1l4fI4lyZLWmrRFIGkruJ2WvWg0vrSxybdpAZxZV3uIA1KPwGoqp2nGWtIAq4DSNLFrbD7254aGJyvT+2G3gBiGuWrLDNDzliATa1KddbA55hl+SeVdaJZtrO6ckwbe7XaaGBttfPQ94pHV6VYjzkT/iP6K+jMhqc=,iv:hWbhqPEoYIIUutCsCeUPk09K8IVCpuz/Z9oa9UC2jq0=,tag:AQNpvSRGD4dFWKFunqMz4w==,type:str]
    version: 3.13.3
