apiVersion: v1
kind: Secret
metadata:
    name: authentik-config
    namespace: authentik
stringData:
    secret-key: ENC[AES256_GCM,data:e8qTR58ddlNbExjr5o+b1aBkDicRaK3oR+lpld5yfusCNaj0g8G3uR4gTtL0HHD2zuK1aF0VySER8cR/kyEuTSDZRKt2Vp3nqlDkaV+aKWEMiuKdQAG81g==,iv:5GqM3KmT3dN5eKZyhcOTEtgvLma8I4u4Hc8LxpUYbwg=,tag:72bP+N0FeJUbAp1AvuwU1g==,type:str]
    bootstrap-password: ENC[AES256_GCM,data:PNvHx6pPlHEpGHaUwwwA5uKSU4Jz/MuYMN4RvrnMgdRf5EKhD/wSecWGjiDbNR19,iv:xusZxi6Nk2/5dj/cO0IFrjT1Rf/SrZftaH2vKZ6vAYU=,tag:WTSzebyyKLg7AeWSvLXReg==,type:str]
    bootstrap-token: ENC[AES256_GCM,data:rVWPoE7sjbo+Tu90is3X+qZgi7xbTZzgsBnnEG2gI1OpUkQ0jMHDN3596ggMLRxtkjOrbcrh3pMvXLRxaGz15w==,iv:01SnaIbrKruYr4SkznV2JU57HdestaKYl0iGHyigd7M=,tag:hy9FXHV7uOYRHSao3iTA5w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEbUg1TjQzb0JkZ0FRb2l4
            ZkQwSkpXUjJyKzBrOFVCdWpmbitTUVNsL3k0ClBWOWhQV3Q1Tm11WUFwK1h5eHhp
            K3hQS25MYTJ1QUhuYzhYemE4YzdXRGsKLS0tIGo5cEpJSjNscXRuZGwwaDNoVmc5
            UmxTWWYyUy81ejQ1SzRjSmxTajhBQjgKald1XDTHjTu3c98glv5czgfNf9rHawAn
            wkGK0VGPA14Y4N3nMie0R3e/oBuMvUercSSEnsohWLY279fgdeqw+g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wp3ddrp7tj36gvutrxaj42q8azjfxg7dda8g0cxm0n3njyxaeaaqv3vu4k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-28T18:29:10Z"
    mac: ENC[AES256_GCM,data:kGkYCQ7oT0G6um/gXv2zCiieHxUwfPCDMMMuAcAwq84D07e3XOk24UfDJ5Ln1ZY69XSsN2IqhMj9kHoHqnwxD2wMqG9DdqggHuUHnEMcYqJLbnDrSwB2GfcLHwQm1ucWrlu8s/51GoR2dGOKcAlLCzZtvke6vPKPaGT4rkIqZaA=,iv:RHsTIWDtPxOdtnlSgYdFo6kK75jooMIj1/6pfl8Vdgw=,tag:J5X5lrCN6wsrkPhbzuDFoQ==,type:str]
    version: 3.13.3
