apiVersion: v1
kind: Secret
metadata:
    name: authentik-postgresql
    namespace: authentik
stringData:
    postgres-password: ENC[AES256_GCM,data:Z0PTSBvDMsyNK1ONn9/bIkhqsil07H/xDQpX3xZZenpopbO7RKQeCfw2yK6yfw/a,iv:QTtr8tH6m4wmU4bN2gdTCN/CRT2OB+CIl2+nV3nBO8c=,tag:JSIRaDrI32bC4ncxZ1acPg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPUWhkdmUybElIc1Vqd0lj
            dVZIVWJaT1kwTnFjZVdITnB6ZStVcU1OamhjCmtOYzdWN2djQ2NFZmp6Smc2ZE5C
            Rm9hSVhsN3RJVjNPcG12YWdaWkhWdXMKLS0tIFZrUCtFV20yaTc1NlcwNUcvMW0w
            d1lMWmlLTExZUE9zVjlDMUlOalJpd0kKZS9z3PPkNI0y9hdyuv9CCt8uFtqFF1pG
            rAOzDLlYoRbfcGoS+X1KpGYDvmoWdnohK03SLcs0Fll7gmzfTc7yYA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wp3ddrp7tj36gvutrxaj42q8azjfxg7dda8g0cxm0n3njyxaeaaqv3vu4k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-28T18:29:10Z"
    mac: ENC[AES256_GCM,data:OB2JaqLvmDbbZ4zcKMvCIGOZVdt/SOdYqtGjSA5M1jGW1f4bsQwC9WbIVIHzLZlIxctHpodDwfAb3k9glVjHoPenDDtVtpkhWDO5qHQuJdhfj0b3ZQJ6QDVEV6IpNGrBQ6Qe3c29B768VDacINH07gbsykKQfiZAAgOG61lLI2Y=,iv:vo5Rl2Xj7PrpmiwdvXqDOsfWkcRhXxwtlh4qRzRo1UA=,tag:iq0SR+o+mNv1QKoddqheng==,type:str]
    version: 3.13.3
