apiVersion: v1
kind: Secret
metadata:
    name: authentik-postgresql
    namespace: authentik
stringData:
    postgres-password: ENC[AES256_GCM,data:H7UHAMa3mF5XlwxVAqt9a/raohjhJneChfUKd8w2lEI=,iv:KcS0hwMMXBIJlU5oQ5/h61PdeqF6Ps5y/mtJYsFfDJQ=,tag:xaQbo4wjzwpBPDivjLdHiw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFbnY0KzNMNWJSem00aGhN
            Q1l3UDY2cTRMU3N6TUVyL0hOUGk2SVlTMzB3CktQOFNRZ0plTGc4czA1Q3ZKUFlw
            TFl2UkRBU0xSTFdiNC9RVDFjRnhJcTAKLS0tIFlCRmZrUytaQVNLSXAwb1lIanND
            MW5rczloNkRQbG1BemZRWWxySjJjd2sK0TooZLaXemSxAeWGGctoL+lFNFB1CSg+
            ZcCw+DL3acxhNIs59inC69/zNo3OYPionEBLV2Lo9zHNcZoEsDRnvw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gfycq3cyvq29hwkluywkhyc6rpt9y257u9ltltea769khtkysawslec0vw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-19T05:53:59Z"
    mac: ENC[AES256_GCM,data:OlGWp0p8zuG7nOoVqmG9+prBTpz+6pUcIjDeA/RX3aaaHEkyfMyklcsZbPuH1p7K1WMTln0616iHLmLkmRMPd7bs7COCtPw0Tz6xZbZm9gplASNY4PvgsZirQO7MXhGvGvTx5AwXBEV8XoV3eK1ycomPQ5MkASltGV8U1gfI+z4=,iv:nJ7QtowrkK+F9Z4uB239FG7ethWDhAdTQo8/ITUgA+4=,tag:Dsts5JxRYDjdXvHgSIpjKQ==,type:str]
    version: 3.13.3
