apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: observability
stringData:
    admin-user: ENC[AES256_GCM,data:hiJPZiM=,iv:uEKm0G1fVe/M4pyeIESQs5IOE/eKNVjYhijb7pf0AEA=,tag:KQ5Ce46nWjXjpuBCe91NLw==,type:str]
    admin-password: ENC[AES256_GCM,data:6S6iuw8EWgC17R84ppn8YMbUFDB7nS4lS6jTTDYBmFKjaviETUUvN2B0W3QDIgyR,iv:OjQM9nuEXuMQDWbAtIDHT+ykNnCZ1YiMIO9KMz0zTuU=,tag:6iaHuKaExWWeG9AqJrX/8g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBMm1BNXQydmhiT2FuMlJY
            bFU5VGE5OFN3OWlKcFVSZlM3WVJ0RkliVFhjClVraGRkZVFxekhmaDFkajJoY2RL
            QkUrWUxIVjFZOGxzRXMxOHpnL3hzVTgKLS0tIDVYYkUxU29wUmVGNmdXWHJzWmxN
            VzU3R1JDM3ArYThXZTZ1Qml6SXFXbkEKpJIeTnqAKzcmUWZjJj5gTzeE5MCY7gvS
            1N7g+ooXqLN4i6zoXW5+sgR/3kIbl398Grwl0szAAiOgeCkCPPN8qg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wp3ddrp7tj36gvutrxaj42q8azjfxg7dda8g0cxm0n3njyxaeaaqv3vu4k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-28T18:29:10Z"
    mac: ENC[AES256_GCM,data:8ry0Gvnt8fGZtUAqJ+bnRdREUTW3d/7GXl0uZkd1TfJ2iVeVgzh3U9dvezj8gJkYB7XvglJClmvJwTnWmBPPGLBuyhXOfpszBDRbFKE+d/40tr/eRgDFRg7Bz7Janygxu4atVKyvmxLdLVDwZourLDAsiw8IS1tZNcQPA/PYAUw=,iv:M5rjnEt801ocova1xRAIZj7pcNfmDArIppG8Asqnrj0=,tag:qD6eQVUzfr2LFVj6aPiWsw==,type:str]
    version: 3.13.3
