apiVersion: v1
kind: Secret
metadata:
    name: grafana-oidc
    namespace: observability
stringData:
    client-secret: ENC[AES256_GCM,data:SyEymINHyqD86AYYDbiAFA4VdWV/cRDqE8mbqfmUKPqEBrqhLlAyUEtSUL0lD3nrEbIgpnkrBQluCWBbGk1jIg==,iv:PGJK4F1+V5e3BBHIRY3vlwN1NrWwp7ghNjyLB5g74/M=,tag:MjjH+NNqnQMSnFR0sMa0Qg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRVEhERjZiZngvTk5QVzhw
            cWw1MUN0NkFuVjNmb0FXVjVuU0VDYTBYdFc4CnlsTzBwcms2NHJlZXlFRTNOMGN0
            Mkh6M0pFVE8wWDJPb3JUSFp6OS9Ea1EKLS0tIDlvQzFZMklUR0Q4cHYzWFNRMEt4
            VUFWczBrcmxyeWNkaDAwMjQxakZLTncKgZy6jiusoDFv2SDCBJjZLd+zxMc8YNuu
            lX2fQzfE5/MMiOlxQZjJhPAvCSvS20RX/+MxV01DmCZhN5NF/md4GA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wp3ddrp7tj36gvutrxaj42q8azjfxg7dda8g0cxm0n3njyxaeaaqv3vu4k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-28T18:29:10Z"
    mac: ENC[AES256_GCM,data:PmSUB2ZWBFzMHxYVOVZOvA1tmOgfCNijTs6l788h9yoeXjXQUmHQmBaE/ojMALOErXQqTRbRnBtdd5XK3jv1NGTXLe3O/ixDGmPU05a5NYijmD3WTIoI8I33ezPq/5Dm2dHS8eVIgQFOolBjOir3ga/LiDiT3RBZjE57eBHNznI=,iv:N7/46GNqyWSBiMdvHo8eCp8Zhrt+FUMPicbsC6DFiiY=,tag:aMB4Sd4wmIJDelDvum/vEw==,type:str]
    version: 3.13.3
